global:
  scrape_interval: 15s

scrape_configs:
  # Flask 애플리케이션의 메트릭 수집
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi-app:5001'] # Docker for Mac/Windows인 경우; 리눅스에서는 'localhost:5000' 또는 컨테이너 네트워크 이름 사용

  # 시스템 메트릭 수집 (node-exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

remote_write:
  - url: 'http://influxdb:8086/api/v2/write?org=opensource&bucket=mydb&precision=ns'
    bearer_token: 5Yaj0YmESH5nzBx0k6ff3a_18mJp1aaXUoWl1ISr93gONKjITK8tADZjRlLt71tD91Y3cfWFj09H6s5Wl8atkw==
